# Generated by Django 3.1.7 on 2021-03-28 16:32

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Porfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1)),
                ('image_project', models.ImageField(upload_to='img/porfolio')),
                ('name_project', models.CharField(default='', max_length=25)),
                ('short_description', models.CharField(default='', max_length=100)),
                ('long_description', models.TextField(default='')),
                ('source_code', models.URLField(default='')),
                ('technologies', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=53)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='title')),
                ('image_blog', models.ImageField(upload_to='img/blog')),
                ('short_blog_description', models.CharField(default='', max_length=320)),
                ('long_blog_description', models.TextField(default='')),
                ('publish_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
