# Generated by Django 3.1.7 on 2021-03-29 00:56

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='image_blog',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='blog-images'),
        ),
        migrations.AlterField(
            model_name='porfolio',
            name='image_project',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='porfolio-images'),
        ),
    ]
